### ISSUE TITLE
Interesting Fetch Injector

### ISSUE THREAD

**Issue by zoomclub** [jpex-js/vue-inject#9]
Just noticed this new injector that injects Scripts and CSS. I'm not sure if it has considered the VDOM and how it might work in Vue? Nonetheless, the ability to fetch remote artifacts of different types at runtime is very useful, could vue-inject encompase such functionality?

https://github.com/jhabdas/fetch-inject
https://hackcabin.com/post/managing-async-dependencies-javascript
https://medium.com/@jhabdas/webpack-is-your-achilles-heel-d3cd80821a4f

**Comment by jackmellis** [comment]
That is interesting. I had been thinking about the best way to have dynamically-loaded dependencies in a pre-compiled environment like *webpack*.  

The underlying *jpex* library is able to work out when you're requesting a node module when used in node, but on the web, it's more complicated as webpack & co expect you to provide a predefined list of modules to use (or it tries to guess based on relative folder paths etc.).

It would be nice if something like this could be incorporated, where instead of a registering a factory function, you just provide a url to an external script. vue-inject resolves stuff synchronously, though, so that could get tricky.

I'll probably have a play with fetch-inject and see how easily it could fit into the picture. Feel free to add any thoughts you might have had on how this would work...

I can't see the virtual dom being an issue myself, it's only the same as Single File Components attaching style tags to the `<head>` I suppose, or webpack's JSONP module splitting...
